# Generated by Django 4.2.6 on 2023-11-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_metodopago_direccionenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionenvio',
            name='ccomuna_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='direccionenvio',
            table='DireccionEnvio',
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table='MetodoPago',
        ),
    ]
