# Generated by Django 4.2.6 on 2023-11-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_carrito'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrito',
            table='Carrito',
        ),
    ]
