# Generated by Django 4.2.6 on 2023-11-16 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categoria_alter_review_table_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
