# Generated by Django 4.2.6 on 2023-11-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
