# Generated by Django 4.2.6 on 2023-11-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_producto_cantidad_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='../media/imagen_products/'),
        ),
    ]
