# Generated by Django 4.2.6 on 2023-11-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_producto_cantidad_stock_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='./media/imagen_products/'),
        ),
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
