# Generated by Django 4.2.6 on 2023-12-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_producto_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
    ]
