# Generated by Django 4.2.6 on 2023-12-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_producto_imagen_alter_review_table'),
        ('products', '0011_remove_producto_usuario'),
    ]

    operations = [
    ]
