# Generated by Django 4.2.6 on 2023-12-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_usuario_producto_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='user',
            new_name='usuario',
        ),
    ]
