# Generated by Django 4.2.6 on 2024-03-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='code',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
